site_name: Datapreparer
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
nav:
  - What is Datapreparer?: 'index.md'
  - Quick Start: 
      - Install Datapreparer: 'quick-start/install.md'
      - Setup Datapreparer: 
          - Vscode Setup: 'quick-start/vscode-setup.md'
          - IntelliJ Setup: 'quick-start/intellij-setup.md'
          - Terminal: 'index.md'
      - Starter Example: 'quick-start/starter-project.md'
  - Guides:
      - Data preparation process: 'guides/data-prep-process.md'
      - Adding data:
        - Overview: 'guides/adding-data/intro.md'
        - From CSV files: 'guides/adding-data/CSV.md'
        - From local databases: 'guides/adding-data/local-DB.md'
        - From JSON files: 'guides/adding-data/JSON.md'
        - From the web: 'guides/adding-data/external-uri.md'
      - Viewing data (Data Context): ''
      - Setting priorities (User Context): 
          - Motivation: 'guides/setting-priorities/intro.md'
          - Using Criteria: 'guides/setting-priorities/criterias.md'
          - Using Filters: 'guides/setting-priorities/filters.md'
      - Refining solutions: 
          - Motivation: 'guides/refining-solutions/intro.md'
          - Feedback: 'guides/refining-solutions/feedback.md'
          - Steering: 'guides/refining-solutions/steering.md'
  - Advanced Usage:
      - Command line tool: 'index.md'
      - Scenarios: 'index.md'
      - Wrangle properties: 'index.md'
      - Web security: 'advanced/web-security.md'
  - Pipeline:
      - Brief Overview: 'index.md'
      - Transducers:
          - Match: 'index.md'
          - Repair: 'index.md'
          - Transform: 'index.md'
          - Profile: 'index.md'
          - Map: 'pipeline/map.md'
          - Select: 'pipeline/select.md'
  - Open Source Self Help: 
      - Project Structure: 
          - Spring Setup: 'spring-setup.md'
      - Contributing: 'index.md'
plugins:
  - search
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - attr_list
extra_css:
  - extra.css
