site_name: Datapreparer
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
nav:
  - What is Datapreparer?: 'index.md'
  - Quick Start: 
      - Install Datapreparer: 'quick-start/install.md'
      - Setup Datapreparer: 
          - Vscode Setup: 'quick-start/vscode-setup.md'
          - IntelliJ Setup: 'quick-start/intellij-setup.md'
          - Terminal: 'index.md'
      - Starter Example: 'quick-start/starter-project.md'
  - Guides:
      - Data preparation process: 'index.md'
      - Adding data:
        - Importing CSV data: 'guides/adding-data/CSV.MD'
        - Connecting to an external database: 'guides/adding-data/external-DB.MD'
        - JSON support: 'guides/adding-data/JSON.MD'
      - Setting priorities: 
          - Using Criterias: 'index.md'
          - Using Filters: 'index.md'
      - Refining solutions: 
          - Feedback: 'index.md'
          - Steering: 'index.md'
  - Advanced Usage:
      - Command line tool: 'index.md'
      - Scenarios: 'index.md'
      - Wrangle properties: 'index.md'
      - Database connection: 'index.md'
      - JSON support: 'index.md'
      - Web security: 'index.md'
  - Pipeline:
      - Brief Overview: 'index.md'
      - Transducers:
          - Match: 'index.md'
          - Repair: 'index.md'
          - Transform: 'index.md'
          - Profile: 'index.md'
          - Map: 'index.md'
          - Select: 'index.md'
  - Open Source Self Help: 
      - Project Structure: 
          - Spring Setup: 'spring-setup.md'
      - Contributing: 'index.md'
plugins:
  - search
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - attr_list
extra_css:
  - extra.css
